title: Jade Santiago # your name (or website title) here
logo: "/images/jade.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Estudante de licenciatura em ciências biológicas na Universidade Federal de Viçosa - Campus Florestal.
  <br>
  Atualmente, venho me dedicando ao estudo da linguagem R e sua aplicação em inferências estatísticas em dados biológicos, com a intenção de contribuir para o desenvolvimento de pesquisas.
  <br><br>
  <a href="https://wwws.cnpq.br/cvlattesweb/PKG_MENU.menu?f_cod=9916B35EA146B54C8364DA7F1F8F336F#/">Você pode vizualizar meu Lattes aqui</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
