title: Jade Santiago # your name (or website title) here
logo: "/images/eu2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Olá, meu nome é Jade Santiago, sou estudante de licenciatura em ciências biológicas na Universidade Federal de Viçosa - Campus Florestal e estou atualmente no 6º período. 
  <br>
  Meu interesse em bioinformática com enfoque na bioestatística surgiu ao perceber como a tecnologia pode auxiliar na análise de dados biológicos, e estou em busca de aprimorar minhas habilidades nessa área 
  <br><br>
  Atualmente, venho me dedicando ao estudo da linguagem R e sua aplicação em inferências estatísticas em dados biológicos, com a intenção de contribuir para o desenvolvimento de pesquisas na área de biologia
  <br><br>
  <a href="https://www.linkedin.com/in/matt-chapman-ba8488118/">Você pode vizualizar meu Lattes aqui</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
